/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panayotis_jerminal_TermWindows */

#ifndef _Included_com_panayotis_jerminal_TermWindows
#define _Included_com_panayotis_jerminal_TermWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panayotis_jerminal_TermWindows
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_panayotis_jerminal_TermWindows_getWidth
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
